name: Bump Version

# The action uses the GitHub App token to create a tag and push it to the repository.
# This is required because the default GITHUB_TOKEN does not trigger other actions, such as the publish action on tag push. 

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: "Generate Short Lived OAuth App Token (ghs_*)"
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      id: app-token
      with:
        app-id: "${{ secrets.BPG_APP_ID }}"
        private-key: "${{ secrets.BPG_APP_PRIVATE_KEY }}"
        owner: "${{ github.repository_owner }}"
        repositories: "${{ github.event.repository.name }}"

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c # 1.73.0 
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        WITH_V: true
