name: Bump Version

# The action uses the GitHub App token to create a tag and push it to the repository.
# This is required because the default GITHUB_TOKEN does not trigger other actions, such as the publish action on tag push. 

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: "Generate Short Lived OAuth App Token (ghs_*)"
      uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
      id: app-token
      with:
        app-id: "${{ secrets.BPG_APP_ID }}"
        private-key: "${{ secrets.BPG_APP_PRIVATE_KEY }}"
        owner: "${{ github.repository_owner }}"
        repositories: "${{ github.event.repository.name }}"

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297 # 1.71.0 
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        WITH_V: true
