---
name: "Scheduled: Cleanup"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

permissions:
  packages: write

jobs:
  cleanup:
    name: Cleanup untagged images
    runs-on: ubuntu-latest
    steps:
      - name: "Generate Short Lived OAuth App Token (ghs_*)"
        uses: actions/create-github-app-token@v1.6.2
        id: app-token
        with:
          app-id: "${{ secrets.BPG_APP_ID }}"
          private-key: "${{ secrets.BPG_APP_PRIVATE_KEY }}"
          owner: "${{ github.repository_owner }}"
          repositories: "${{ github.event.repository.name }}"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ steps.app-token.outputs.token }}"

      # - name: Delete all containers from package without tags
      #   uses: Chizkiyahu/delete-untagged-ghcr-action@v3
      #   with:
      #     token: ${{ steps.app-token.outputs.token }}
      #     repository_owner: ${{ github.repository_owner }}
      #     repository: ${{ github.repository }}
      #     untagged_only: true
      #     owner_type: user
      #     except_untagged_multiplatform: true

      - name: Prune containers
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: "${{ steps.app-token.outputs.token }}"
          organization: "${{ github.repository_owner }}"
          container: "${{ github.event.repository.name }}"
          dry-run: true # Dry-run first, then change to `false`
          keep-younger-than: 7 # days
          keep-last: 2
          prune-untagged: true
